### ISSUE TITLE
Command help for cg provider is misleading

### ISSUE THREAD

**Issue by nielspardon** [cloudgraphdev/cli#10]
**Describe the bug**

The CLI help instructions for `cg provider` currently look like this:

```
$ cg provider 
Commands to manage provider modules, run $ cg provider for more info.

USAGE
  $ cg provider:COMMAND

COMMANDS
  provider:add      Add new providers
  provider:install  Install providers based on the lock file
  provider:list     List currently installed providers and versions
  provider:remove   Remove currently installed provider
  provider:update   Update currently installed providers
$
```

One would think that you can e.g. run `cg provider:list` to get a list of all the providers however running this command will fail:

```
$ cg provider:list
 ›   Error: command provider:list not found
$
```

What does actually work is `cg provider list`:

```
$ cg provider list
ℹ Found config for cloudGraph, using...
ℹ Dgraph host set as: http://localhost:8997
✔ Provider aws@0.59.1 is installed
$
```

**To Reproduce**
1. Run e.g. `cg provider:list`

**Expected behavior**

Either make `cg provider:list` work or change the help text to show `cg provider list` instead :-)

**Environment (please complete the following information):**
 - CLI version @cloudgraph/cli/0.15.5 darwin-x64 node-v16.13.1
 - Context local machine

**Comment by tyler-dunkel** [comment]
Sorry for the really long lead time on this but it was finally completely finished in Oclif and should be fixed on CG version `0.21.1`. Thanks for reporting!
