### ISSUE TITLE
CIS GCP 1.3 support

### ISSUE THREAD

**Issue by jessequinn** [cloudgraphdev/cli#101]
CIS has updated GCP CIS to 1.3. Will this be added soon?

**Comment by tyler-dunkel** [comment]
Hi @jessequinn, thank you for your interest in CG. We have GCP CIS 1.3 on our roadmap for policy packs and will be adding it soon. Ill keep you updated here

**Comment by tyler-dunkel** [comment]
Support for GCP CIS 1.3 should be ready by end of October!

**Comment by tyler-dunkel** [comment]
Hi @jessequinn this policy pack is now supported!
