### ISSUE TITLE
CloudQuery Dgraph Destination?

### ISSUE THREAD

**Issue by yevgenypats** [cloudgraphdev/cli#109]
Hey folks!

Im Yevgeny, Founder @ [CloudQuery](https://github.com/cloudquery/cloudquery) (which you might be familiar with :) ). We recently have number of security and cost vendor migrated to use our ELT engine under the hood so they can focus solely on the business, analysis and visualization logic on top.

I don't know if this is something relevant at this stage but if yes, we could look at adding DGraph to our [destinations](https://www.cloudquery.io/docs/plugins/destinations/overview), which should fit your use-case with minimal schema changes hopefully.

Best,
Yevgeny

**Comment by rewanthtammana** [comment]
Nice one, @yevgenypats!

**Comment by tyler-dunkel** [comment]
Hi @yevgenypats, thanks for reaching out! We are currently planning on staying with our current system but would be happy to look deeper into CloudQuery if more destinations were supported.

**Comment by yevgenypats** [comment]
> Hi @yevgenypats, thanks for reaching out! We are currently planning on staying with our current system but would be happy to look deeper into CloudQuery if more destinations were supported.

Sounds good! Which destinations are important for you? (Apart from Dgraph?)

**Comment by tyler-dunkel** [comment]
Let me think on that, Dgraph would be a good start!
