### ISSUE TITLE
possible to query launch time for ec2 as well?

### ISSUE THREAD

**Issue by borgified** [cloudgraphdev/cli#11]
would like to be able to query for ec2 instances that had launch time prior to X date. with aws cli, i can do something similar to

```
aws ec2 describe-instances  --query 'sort_by(Reservations[].Instances[], &LaunchTime)[:-1].[InstanceId,PublicIpAddress,LaunchTime]'
```
to obtain launch time but it seems the cg scan doesn't pick this up yet.

**Comment by tyler-dunkel** [comment]
@borgified thanks for bringing this up. We will look into if we dont currently have that data and can add it into the ec2 schema. @m-pizarro can you take a look at this?
