### ISSUE TITLE
Unable to see any results in UI for queryawsCISFindings

### ISSUE THREAD

**Issue by rewanthtammana** [cloudgraphdev/cli#111]
**Describe the bug**
I've followed the instructions in README to install `aws-cis-1.3.0` policy and execute the scans. The scan was successful but I'm unable to query the cis findings.

The output shows it identified some issues but I'm unable to query them
![image](https://user-images.githubusercontent.com/22347290/221829759-9564aad7-98d1-428d-aff0-134a043bebd6.png)

I can see some data inside dgraph container,
![image](https://user-images.githubusercontent.com/22347290/221831998-fc99fe36-cfeb-4397-83dd-3ce81ce33fe8.png)

But when I try to query with graphql, the results are nil.
![image](https://user-images.githubusercontent.com/22347290/221829420-cc6b56e9-2abd-4fe0-a1dd-b85dea537276.png)

**To Reproduce**
1. Started docker instance for dgraph
    ```bash
    docker run -d -p 8995:5080 -p 8996:6080 -p 8997:8080 -p 8998:9080 -p 8999:8000 --label cloudgraph-cli-dgraph-standalone -v /Users/rewanthtammana/.local/share/cloudgraph/dgraph:/dgraph --name dgraph dgraph/standalone
    ```
2. Initialized cg, `cg init`
3. `cg policy add aws-cis-1.3.0`
4. `cg scan aws`
5. The scans are successful but unable to query cisbenchmarks from graphql database

Please include the `cg-debug.log` file if applicable

**Expected behavior**
`queryawsCISFindings` is expected to return the identified results.

**Environment (please complete the following information):**
 - CLI version: `@cloudgraph/cli/0.25.1 darwin-x64 node-v16.0.0`
 - Provider versions: `aws@0.85.1` & `aws-cis-1.3.0 module version: 0.4.0`
 - Context: Local machine

**Comment by tyler-dunkel** [comment]
Hi @rewanthtammana thanks for letting us know. It looks like there was an issue inserting the data into Dgraph. We will take a look!

**Comment by rewanthtammana** [comment]
It would be really helpful, if there's a verbose option that helps us to understand the kind of errors we are facing while inserting data into the dgraph database.

**Comment by tyler-dunkel** [comment]
Hi @rewanthtammana, we actually do have a verbose option you can use! If you set the env variable `CG_DEBUG=5` you will get a lot more info on the error. So you can run `CG_DEBUG=5 cg scan aws` for example.

**Comment by rewanthtammana** [comment]
Thanks! I was looking in the flags for debug/verbose option but only found `--dev` but it didn't help much with debugging. I will try this out.
