### ISSUE TITLE
Can't install modules (with cg init)

### ISSUE THREAD

**Issue by jebotz** [cloudgraphdev/cli#118]
I followed the installation instructions on (from the GitHub README) to the letter, but when I do "sg init gcp" I get this:

```
$ cg init gcp
\u2139 Found config for cloudGraph, using...
\u2139 Dgraph host set as: http://localhost:8997
\u2139 No lock file found for Cloud Graph, creating one...
\u2139 Installing gcp module version: latest
\u2716 Manager failed to install provider plugin for gcp
\u2716 **Error: provider gcp module check FAILED, unable to find plugin**
\u26a0 There was an error installing or requiring a plugin for gcp, does one exist?
\u2139 For more information on this error, please see https://github.com/cloudgraphdev/cli#common-errors
\u26a0 There was an issue initializing gcp plugin, skipping...
\u2139 CloudGraph config found...

```
I tried "cg init aws" and get the same error.

**Comment by tyler-dunkel** [comment]
hmm that is odd. Please run the command in debug mode and paste those logs. `CG_DEBUG=5 cg init gcp`. You can also try running the command in `sudo`

**Comment by jebotz** [comment]
Yeah, that's it, or part of it.  My nodejs / npm are from system packages (Ubuntu 22.04), so it needs root to install.  Then it gets further but then breaks with other errors because nodejs version is too old.  I'll have to start over with newer nodejs, so go ahead and close this bug report.

**Comment by tyler-dunkel** [comment]
sounds good let me know if you encounter a further issue!
