### ISSUE TITLE
Error while running cg init

### ISSUE THREAD

**Issue by shreedharn-cbm** [cloudgraphdev/cli#5]
cg init is run on an ec2 instance. The instance does not use any credential files instead uses roles.

Following is the output while running cg niti.
ℹ No lock file found for Cloud Graph, creating one...
 Installing aws module version: latest
⠧ Installing aws plugin(node:12370) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /home/ec2-user/.nvm/versions/node/v16.10.0/lib/node_modules/@cloudgraph/cli/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ aws plugin installed successfully!
ℹ aws version locked at: 0.28.2
✖ There was an error writing latest version to the lock file
⚠ Unable to read AWS shared credential file
? Select regions to scan us-east-1, us-east-2
✔ 🎊 AWS configuration successfully completed 🎊
    TypeError: Cannot read properties of undefined (reading 'join')

**Comment by tyler-dunkel** [comment]
Hi @shreedharn-cbm ! thanks for giving CloudGraph a shot! We currently do not support running CG on an ec2 instance (although it may be possible right now and we are planning to support it in the future). I see 2 issues happening here. 
1. "✖ There was an error writing latest version to the lock file" - are there permissions to write to the file system in place on the ec2 (for the user running the cg command)? 
2. "⚠ Unable to read AWS shared credential file" - we currently try to use the credentials files OR credentials set in the ENV and if those arent found we allow the setting of credentials manually. We are hoping to support role based credentials soon.
3. "TypeError: Cannot read properties of undefined (reading 'join')" - We will look into this error and try to fix it. Thanks for bringing it to our attention!

**Comment by tyler-dunkel** [comment]
Thanks for providing this additional context. I have a PR open to resolve the lock file issue. It should be merged soon. Regarding the AWS roles. I am going to take this one and try to get it done next week.

**Comment by tyler-dunkel** [comment]
@shreedharn-cbm I have completed the work for running CG on an EC2 and it is in PR now. We hope to merge it today. Once merged, ill ping here again. At that point, please go through these steps to give it a shot. Thanks!:

```
npm i -g @cloudgraph/cli
cg update
cg init
```
for CG init you will get a question like:

`Do you want to provide a role ARN for this identity to assume?`

In order to use your EC2's default credentials, answer `N` for this question.

You will then get a question like:

`Configure another AWS account?`

You can answer `N` for this one as well.

Then you can go through the rest of the init flow (regions question).

After this, run `cg scan` to scan the AWS account given the default EC2 credentials.

Please let me know if you have any issues with this and thanks again!

**Comment by tyler-dunkel** [comment]
Damn, almost there! lol 

for cloudtrail: I will create a ticket and investigate this. Do you have multiple cloud trails in this account that share an arn?

for the query engine: Did you happen to kill the process after scan was done running? (The scan command starts an express server for serving the query engine but the express server will stop if the process is killed)

**Comment by shreedharn-cbm** [comment]
- aws module version: 0.34.1 (got the recent version)
- There are multiple cloudtrails and theirs arns were printed out
- cg scan terminates after the execution is completed.

Is there any way to limit scanning to a specific vpc or specific resources: such as EC2 or S3
Apart from regions there appears to be no option in  cg init.
Following command does not work either:
```
cg init aws -r ec2Instance
```

**Comment by tyler-dunkel** [comment]
Ok thank you.

There is a way to limit scanning to specific services and it is to use the `-r` flag which is a boolean flag. Try running
`cg init -r` and you should see a prompt to select services to scan like below:

![image](https://user-images.githubusercontent.com/7192733/137202355-0dcc1f89-d801-4cdd-a50d-f467d34e3c5b.png)

Please let me know if you do not see it, and thanks for helping us debug this!

Regarding the cloudtrails: were the arns all different?

**Comment by tyler-dunkel** [comment]
@shreedharn-cbm sorry to be late following up on this. We have released the RDS service (clusters and instances) which should allow you to run compliance checks on RDS (such as if the db instances are encrypted). See the docs here for the fields of the rds service schemas and some example queries: https://docs.cloudgraph.dev/providers/aws/services/rdsDbInstance

**Comment by tyler-dunkel** [comment]
@shreedharn-cbm as this issue is resolved (btw we also resolved the cloudtrail issue you reported) I am going to close for now. Please open a new issue if you have any problems and thanks again!
