### ISSUE TITLE
Select all aws profiles

### ISSUE THREAD

**Issue by augusto-gregorio** [cloudgraphdev/cli#6]
Is there any way to select all the aws accounts i have configures in the aws cli? because i hace 188 accounts, and adding one by one with "cg init" is a pain. Maybe by editing the configuration file and adding the accounts manually?

**Comment by tyler-dunkel** [comment]
Hi @augusto-gregorio, thanks for giving CloudGraph a try! and yes I can see how that could be tedious. We may look at adding a way to configure all your accounts at once as an enhancement in the future. For now, I believe editing the config file manually and adding your accounts would be the best method. The accounts go under the array at `aws.accounts: []` in the config file. The path to the config file can be found at the bottom of running `cg init` and typically has a structure like `~/.config/cloudgraph/.cloud-graphrc.json`. In an account object, you can configure a `profile`, `roleArn` and/or and `externalId` which the tool will use to extract the right credentials using the AWS credential provider chain. 

Please let me know if you have any trouble adding them!

**Comment by augusto-gregorio** [comment]
I added a lot of them to the config file and worked perfectly.

Thanks a lot Tyler.
