### ISSUE TITLE
couldn't rewrite mutation addawsDynamoDbTable because failed to rewrite mutation payload because duplicate XID found

### ISSUE THREAD

**Issue by twoerth** [cloudgraphdev/cli#8]
I'm getting a "couldn't rewrite mutation addawsDynamoDbTable because failed to rewrite mutation payload because duplicate XID found" error on a DynamoDB table.

I also get "couldn't rewrite mutation addawsTag because failed to rewrite mutation payload because duplicate XID found" on exactly the same arn.

Looking into the json I could find in the ~/.local/share/cloudgraph/cg/version-X/aws_someid.json, I suspect the issue is linked to the fact that specific dynamodb table has two global indexes which appear in the json file with the arn of the table.

That arn appears as is for 3 things: the table itself and the two global indexes.

Let me know if you need more info on the issue.

**Comment by tyler-dunkel** [comment]
Thank you for reporting this and the through description! We will look into this today. Sorry for the issue!

**Comment by tyler-dunkel** [comment]
@twoerth we just released a fix for this. Please give it a try when you get a chance by doing the following:

run `cg update` (should give you aws provider version `0.40.4`)

try `cg scan` again.

Thanks!

**Comment by twoerth** [comment]
@tyler-dunkel confirmed as working.

Thanks for the fix!
