### ISSUE TITLE
Invalid reference format: repository name must be lowercase

### ISSUE THREAD

**Issue by szgaljic** [cloudgraphdev/cli#90]
Fresh install, failure when running cg launch.

**To Reproduce**

1. npm install -g @cloudgraph/cli
2. cg provider add aws
3. cg init
4. cg launch

```
cg launch
i Found config for cloudGraph, using...
i Dgraph host set as: http://localhost:8997
√ Docker found
√ No reusable instances found
√ Pulled Dgraph Docker image
× Failed starting Dgraph instance
× Error: Command failed: docker run -d -p 8995:5080 -p 8996:6080 -p 8997:8080 -p 8998:9080 -p 8999:8000 --label cloudgraph-cli-dgraph-standalone -v C:\Users\USER\AppData\Local\cloudgraph/dgraph:/dgraph --name dgraph dgraph/standalone:v21.03.1
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
```

    Error: Dgraph was unable to start: Failed starting stopped Dgraph instance

**Expected behavior**

No failure.

**Environment (please complete the following information):**

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19043 N/A Build 19043

```
$ aws --version
aws-cli/2.7.6 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

$ cg -v
@cloudgraph/cli/0.22.0 win32-x64 node-v16.15.1

$ node -v
v16.15.1
```

**Comment by tyler-dunkel** [comment]
@szgaljic hmm I have not seen this issue before. Are you able to launch a Dgraph instance outside of the CG context successfully? The command would be: `docker run -it -d -p 8995:5080 -p 8996:6080 -p 8997:8080 -p 8998:9080 -p 8999:8000 --label testing -v /Users/${username}/.local/share/cloudgraph/dgraph:/dgraph --name dgraph dgraph/standalone:v21.03.1`. Note: you need to create an empty directory at `/Users/${username}/.local/share/cloudgraph/dgraph` first so Dgraph knows where to store data

**Comment by tyler-dunkel** [comment]
@szgaljic following up on this, would you be able to provide more details here? We have not been able to reproduce on our end.

**Comment by tyler-dunkel** [comment]
@szgaljic I am going to close this until more info on this comes in
